# Generated by Django 3.0 on 2022-05-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourhouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Location', 'Location'), ('MaisondePassage', 'MaisondePassage'), ('Vente', 'Vente'), ('Parcelle', 'Parcelle')], max_length=100)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage')], max_length=30)),
                ('profile', models.ImageField(upload_to='')),
                ('salon', models.ImageField(upload_to='')),
                ('salemanger', models.ImageField(upload_to='')),
                ('chambre1', models.ImageField(upload_to='')),
                ('chambre2', models.ImageField(upload_to='')),
                ('chambre3', models.ImageField(upload_to='')),
                ('douche', models.ImageField(upload_to='')),
                ('corridor', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
