# Generated by Django 3.0 on 2022-05-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0002_auto_20220523_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Location', 'Location'), ('MaisondePassage', 'MaisondePassage'), ('Vente', 'Vente'), ('Parcelle', 'Parcelle')], max_length=100)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage')], max_length=30)),
                ('room', models.CharField(choices=[('fourbed', 'fourbed'), ('threebed', 'threebed'), ('twobed', 'twobed'), ('onebed', 'onebed')], max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HouseGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house/images/')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='House.House')),
            ],
        ),
        migrations.DeleteModel(
            name='Fourhouse',
        ),
    ]
