# Generated by Django 3.0 on 2022-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0003_auto_20220525_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locfour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage'), ('Appartements', 'Appartements')], max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('imgone', models.ImageField(upload_to='images')),
                ('imgtwo', models.ImageField(upload_to='images')),
                ('imgthree', models.ImageField(upload_to='images')),
                ('imgfour', models.ImageField(upload_to='images')),
                ('imgfive', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage'), ('Appartements', 'Appartements')], max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('imgone', models.ImageField(upload_to='images')),
                ('imgtwo', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loctree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage'), ('Appartements', 'Appartements')], max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('imgone', models.ImageField(upload_to='images')),
                ('imgtwo', models.ImageField(upload_to='images')),
                ('imgthree', models.ImageField(upload_to='images')),
                ('imgfour', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loctwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage'), ('Appartements', 'Appartements')], max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('imgone', models.ImageField(upload_to='images')),
                ('imgtwo', models.ImageField(upload_to='images')),
                ('imgthree', models.ImageField(upload_to='images')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='housegallery',
            name='house',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='HouseGallery',
        ),
    ]
