# Generated by Django 3.0 on 2022-08-15 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0004_auto_20220807_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('owner_name', models.CharField(max_length=200)),
                ('quarter', models.CharField(choices=[('KIGOBE', 'KIGOBE'), ('KININDO', 'KININDO'), ('KINANIRA', 'KINANIRA'), ('KIBENGA', 'KIBENGA'), ('GASEKEBUYE', 'GASEKEBUYE')], max_length=100)),
                ('status', models.CharField(choices=[('Occupe', 'Occupe'), ('Nonoccupe', 'Nonoccupe')], max_length=50)),
                ('type_maison', models.CharField(choices=[('Simple', 'Simple'), ('Etage', 'Etage'), ('Appartements', 'Appartements')], max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='House.House')),
            ],
        ),
        migrations.DeleteModel(
            name='Locfour',
        ),
        migrations.DeleteModel(
            name='Locone',
        ),
        migrations.DeleteModel(
            name='Loctree',
        ),
        migrations.DeleteModel(
            name='Loctwo',
        ),
    ]
