# Generated by Django 3.0 on 2022-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0005_auto_20220815_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='quali',
            field=models.TextField(null=True),
        ),
    ]
