# Generated by Django 3.0 on 2022-08-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0006_house_quali'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='quali',
        ),
        migrations.AddField(
            model_name='house',
            name='propsalon',
            field=models.BooleanField(default=False),
        ),
    ]
