# Generated by Django 3.0 on 2022-08-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0008_auto_20220824_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='room',
            field=models.CharField(choices=[('four', 'four'), ('three', 'three'), ('two', 'two'), ('one', 'one')], max_length=30, null=True),
        ),
    ]
