# Generated by Django 3.0 on 2022-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('House', '0009_house_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='but',
            field=models.CharField(choices=[('location', 'location'), ('vente', 'vente')], max_length=30, null=True),
        ),
    ]
